-- DEPRECATED: do not execute this file for SIGLA-CMDC.
--
-- The former prototype schema stored records as JSONB and granted anonymous
-- read/write policies. It is intentionally no longer an installation path.
-- Apply the versioned SQL in ../database/migrations and then the matching
-- seed in ../database/seeds through the approved PostgreSQL migration process.
